### ISSUE TITLE
Secret keys should be configurable

### ISSUE THREAD

**Issue by estahn** [cloudhut/charts#11]
We're using the strimzi kafka operator and the secret with the certificate is automatically created by the operator. It would be great to be able to configure the keys for an existing secret, e.g.

```yaml
        secret:
          existingSecret: kafka-cluster-ca-cert
          kafka-tls-cert: ca.crt
```
