### ISSUE TITLE
Unable to use extraVolumes and Mounts

### ISSUE THREAD

**Issue by edgarkz** [cloudhut/charts#32]
Hello,

How should I define values.yaml file to include existing tls configuration
tried with below setup but getting helm related errors:

```
extraVolumes: 
  - name: tls-ca
    secret:
      secretName: kafka-cluster-ca
      items:
      - key: ca.crt
        path: ca.crt
  - name: tls-user
    secret:
      secretName: kafka-user
      items:
      - key: user.crt
        path: user.crt
      - key: user.key
        path: user.key
```
