### ISSUE TITLE
[helm chart] Set log level

### ISSUE THREAD

**Issue by dicolasi** [cloudhut/charts#7]
Ho do i set the log level in values.yaml?

**Comment by weeco** [comment]
You can edit the whole Kowl config here:

https://github.com/cloudhut/charts/blob/master/kowl/values.yaml#L85-L90

accordingly this should be something like:

```yaml
kowl:
  config:
    logger:
      level: debug
```
